<?xml version="1.0" encoding="utf-8"?><Database Name="AlJebal" Class="MenuDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=140.211.126.155;Initial Catalog=AlJebal;Persist Security Info=True;User ID=AlJebalSystemUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AlJebalConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Menus" Member="Menus">
    <Type Name="Menus">
      <Column Name="MenuNum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>